### ISSUE TITLE
About the two dataset you have provided before

### ISSUE THREAD

**Issue by tjsmartlzh** [krrish94/CarKeypoints#11]
Hello!
From previous issues I have noticed that you have provided two datasets (http://www.zeeshanzia.com/dataset/KITTI3D_cvpr17.zip and http://www.nec-labs.com/~mas/DISCO/). However, I noticed that there seems to be some wrong keypoints annotations in both datasets. For example, locations of keypoints in some images are far away where they should be. 
For example, some annotations of keypoints in image in KITTI3D_cvpr17 dataset with path gt_bbx/car_id_69.png are not at where they should be. I feel confused because this dataset is used in 'Deep supervision with shape concepts for occlusion-aware 3d object parsing (CVPR 2017)'. Are there really some problem in the annotations or the way I use the dataset not correct? 

By the way, I used the DISCO dataset for train but found the accuracy in KITTI3D very bad. Have you encountered this problem? Did you use only the DISCO dataset or other dataset? Could you please provide your detail of training using this dataset?

Thank you very much!

**Comment by krrish94** [comment]
Hi @tjsmartlzh 

The two datasets you linked are in-fact provided by the authors on the CVPR 2017 (Deep supervision with shape concepts) papers. Our models in this repo have been trained on our internal dataset (which we're unable to release; hence I pointed to these alternatives).
