### ISSUE TITLE
stack traceback: /root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: in function </root/torch/install/share/lua/5.1/nn/CAddTable.lua:9>

### ISSUE THREAD

**Issue by Robotzeroo** [krrish94/CarKeypoints#13]
Hello, the following problem occurred when I ran the code. My environment is ubuntu16.04, cuda8, cudnn5. Can you give me some suggestions to solve this problem, thank you very much

root@271f5b9d1196:/workspace/CarKeypoints# th inference.lua ./valid.txt ./data/model/model.t7 ./data/result/results.txt
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5
Model Loading...
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5
Model Loading Done
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8321/cutorch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=299 error=8 : invalid device function
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67:
In 2 module of nn.Sequential:
/root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: cuda runtime error (8) : invalid device function at /tmp/luarocks_cutorch-scm-1-8321/cutorch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:299
stack traceback:
        [C]: in function 'add'
        /root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: in function </root/torch/install/share/lua/5.1/nn/CAddTable.lua:9>
        [C]: in function 'xpcall'
        /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
        /root/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        /root/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        inference.lua:111: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
        /root/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        /root/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        inference.lua:111: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50

**Comment by krrish94** [comment]
The model has been trained (and the code has been tested) with CUDA 7 and CuDNN v5. While I don't know for sure, I'd try and run with CUDA 7 if possible.

**Comment by Robotzeroo** [comment]
Thank you for your suggestion! After I switched to cuda7.5, it ran successfully!
