### ISSUE TITLE
training set

### ISSUE THREAD

**Issue by soldierofhell** [krrish94/CarKeypoints#3]
@krrish94, could you provide some more details about the dataset the model was trained on? E.g. is it any of publictly available, what was the size, how where the annotations made (manual/automated way)?

Thank you in advance,

**Comment by krrish94** [comment]
We trained a couple of variants of this network. One of them used the Pascal 3D dataset, which provides keypoint annotations for 12 rigid object categories. Another variant was trained on an in-house dataset, which comprised rendered car images from the ShapeNet dataset. (The second in-house dataset isn't public, but a close parallel can be found in KITTI 3D: http://www.zeeshanzia.com/dataset/KITTI3D_cvpr17.zip )

**Comment by pavan4** [comment]
Could you please share on which dataset, the model released that has been released, trained on?
