### ISSUE TITLE
Request for ASCII mode version of the pretrained model

### ISSUE THREAD

**Issue by hsfzxjy** [krrish94/CarKeypoints#4]
I just failed to load the pretrained model file and got an error like `Failed to load function from bytecode: binary string: not a precompiled chunk /root/torch/install/bin/lua: /root/torch/install/share/lua/5.3/torch/File.lua:314: bad argument #1 to 'setupvalue' (function expected, got nil)`. Seems that something differs between the platforms we use. Would you please provide an ASCII mode model file? Thanks.

**Comment by krrish94** [comment]
The model has been trained (and the code has been tested) with CUDA 7 and CuDNN v5. It could be a problem of a mismatch between your CUDA / CuDNN version.
