### ISSUE TITLE
What's the format of results.txt

### ISSUE THREAD

**Issue by sunying1122** [krrish94/CarKeypoints#6]
Can you explain what's the format about results.txt?
Or How can I use this to draw the 3D wireframe?
I got the following format:
55.25 37.75 3.9218692108989e-05 51.25 43.25 0.00087627675384283 50.25 44.75 -4.2090658098459e-05 ...

**Comment by krrish94** [comment]
Each line of the results file corresponds to keypoints detected over one input bounding box.

We detect 36 keypoints, so you should have for each keypoint the (`x`, `y`) coordinates as well as the softmax confidence score `s`. This makes for a total of `36 x 3` (`108`) entries per line. The ordering of the keypoints is illustrated in the figure (see `README.md`).
