### ISSUE TITLE
Questions about dataset and the prediction of keypoints that can not be seen

### ISSUE THREAD

**Issue by tjsmartlzh** [krrish94/CarKeypoints#7]
Hello! Thanks for the great work on this subject. 
I have some questions about the detection of keypoints that can not be seen. 
I have noticed that this network has the ability to detect the location of all the 36 keypoints regardless the visibility of them. Meanwhile, I downloaded this dataset that you have mentioned in other issues: http://www.zeeshanzia.com/dataset/KITTI3D_cvpr17.zip, but I found that the annotation in this dataset doesn't include the location of the occluded or truncated keypoints. So I want to know whether you have used  other datasets to train the ability to detect the invisible keypoints. If yes, could you please tell me which dataset you used to train this ability of the network?

**Comment by krrish94** [comment]
@tjsmartlzh We rendered a synthetic dataset (using cars from `ShapeNet`) and manually annotated keypoints on 3D CAD models. That allows us to generate annotations even for occluded/truncated keypoints.
