### ISSUE TITLE
About the CPU mode and GPU mode

### ISSUE THREAD

**Issue by BuaaAlen** [krrish94/CarKeypoints#8]
First thanks a lot for your valuable contribution!
If I want to reproduce the results **on a computer which has only a CPU**, please tell me what should I do. Thanks again!

**Comment by krrish94** [comment]
@BuaaAlen Thanks for your interest!
That's a good question, I'm unsure how `lua torch` models trained on GPU can be adapted to CPU. Personally, I haven't had much success and haven't been able to find documentation on this (`lua torch` is no longer actively developed).

It seems very hard to do from this `lua torch` GitHub issue
https://github.com/facebookresearch/wav2letter/issues/4#issuecomment-354837640

**Comment by BuaaAlen** [comment]
Have you published a paper about your work? I want to cite this in my study.

**Comment by krrish94** [comment]
Hi yeah, the following papers might be relevant
*The Earth ain’t Flat: Monocular Reconstruction of Vehicles on Steep and Graded Roads from a Moving Camera* (IROS 2018)
*Reconstructing Vehicles From a Single Image: Shape Priors for Road Scene Understanding* (ICRA 2017)

You can find more about them (and BibTeX entries) here: http://krrish94.github.io/publications/

Thanks for your interest!

**Comment by krrish94** [comment]
Closing, as it seems unlikely to be fixed (lua torch is EOLed too).
